#!/bin/bash

echo 'Waiting 10 minutes for things to start up and settle down...'
sleep 600

# Wait every x number of seconds to run drupal cron
wait_time_in_seconds=10800; # set to 3 hours
while true; do
  echo "Running drush cron"
  drush cron
  echo "Waiting '$wait_time_in_seconds' seconds for next cron"
  sleep "$wait_time_in_seconds"
done
