#!/bin/bash

day_in_seconds=86400;

# Every day do a backup.
while true; do
  echo "Running backup"
  duply site_data backup
  echo "Waiting '$day_in_seconds' seconds for next backup"
  sleep "$day_in_seconds"
done
